### ISSUE TITLE
pennyarcade moved to https

### ISSUE THREAD

**Issue by YogSottot** [vitorgalvao/tiny-feed-scripts#1]
```
/usr/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://www.penny-arcade.com/comic -> https://www.penny-arcade.com/comic (RuntimeError)
        from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
        from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from ./pennyarcade:10:in `<main>'
```

**Comment by vitorgalvao** [comment]
Fixed.
